--Desafio: categorias dos produtos

SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS;


--Desafio: primeiras vendas de um determinado dia

SELECT TOP 10 * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '2017-10-01';


--Desafio: obter a maior venda de um produto

SELECT * FROM TABELA_DE_PRODUTOS
WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao'

SELECT * FROM ITENS_NOTAS_FISCAIS
WHERE CODIGO_DO_PRODUTO = 1101035
ORDER BY QUANTIDADE DESC;


--Desafio: quantidade de vendas

SELECT COUNT(*) FROM ITENS_NOTAS_FISCAIS
WHERE CODIGO_DO_PRODUTO = 1101035 AND QUANTIDADE = 99;


--Desafio: produtos mais vendidos

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS [QUANTIDADE TOTAL] FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO
ORDER BY SUM(QUANTIDADE) DESC;


--Desafio: filtrando os produtos mais vendidos

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS [QUANTIDADE TOTAL] FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO HAVING SUM(QUANTIDADE) > 394000
ORDER BY SUM(QUANTIDADE) DESC;


--Desafio: classificando os clientes

SELECT NOME,
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'Clientes grandes'
	  WHEN LIMITE_DE_CREDITO BETWEEN 150000 AND 110000 THEN 'Clientes médios'
	  ELSE 'Clientes pequenos' END) AS CLASSIFICACAO
FROM TABELA_DE_CLIENTES
ORDER BY NOME;
