--Desafio: separando nome e sobrenome

SELECT SUBSTRING(NOME, 1, CHARINDEX(' ', NOME, 1)) AS [PRIMEIRO NOME], NOME AS [NOME COMPLETO] 
FROM TABELA_DE_CLIENTES;


--Desafio: data por extenso

SELECT NOME + ' nasceu em ' +
DATENAME(WEEKDAY, DATA_DE_NASCIMENTO)  + ', ' +
DATENAME(day, DATA_DE_NASCIMENTO)  + ' de ' +
DATENAME(month, DATA_DE_NASCIMENTO)  + ' de ' +
DATENAME(YEAR, DATA_DE_NASCIMENTO) AS [DATA DE NASCIMENTO]
FROM TABELA_DE_CLIENTES;


--Desafio: formato do faturamento

SELECT YEAR(NF.DATA_VENDA) AS ANO, 
FLOOR(SUM(NF.IMPOSTO * (INF.QUANTIDADE * INF.PRECO))) AS [IMPOSTO PAGO]
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY YEAR(NF.DATA_VENDA);


--Desafio: listando expressão natural

SELECT 'O cliente ' + TC.NOME + ' comprou R$ ' + 
TRIM(STR(SUM(INF.QUANTIDADE * INF.PRECO) ,10,2)) +
' no ano de ' + DATENAME(YEAR, NF.DATA_VENDA)
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC ON NF.CPF = TC.CPF
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY TC.NOME, NF.DATA_VENDA;